# Evento Theme/Blog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MozillaTN Club Name

#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Events

description: > # this means to ignore newlines until "baseurl:"
  MozillaTN ClubName is club under MozillaTN community actively contributing to various contribution of mozilla.

baseurl: "" # the subpath of your site, e.g. /blog
url: https://mozillatn.github.io/clubs

#These settings might be able to go?
author: David Boyne
twitter_username: boyney123
github_username:  boyney123/evento
company_name: Comparethemarket

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html


google_analytics: 'UA-63310670-1'
disqus: true
disqus_shortname: 'MozillaTN'
